### ISSUE TITLE
Lag Spikes from GBooster

### ISSUE THREAD

**Issue by cobrex1** [TamrielNetwork/GBooster#36] opened 2022-03-21 17:30 UTC
Hi and thanks for the updates.

Having loaded 1.4.1 onto my servers, re-set the config and adding in the additions from the previous config, re-booted the servers and every 10 mins there is a heavy lag spike with GBooster taking server TPS. This last for a minute and then TPS returns to normal. Ran the timings report for 1 hour.

I have copied the timings report. Disabled the plugin and no lag spikes.

https://timings.aikar.co/?id=ac213913e1154960be4874b0317529ee#plugins

**To Reproduce**
Install 1.4.1 on paper 1.18.2 number 260+

**Comment by TamrielNetwork** [comment] 2022-03-21 18:24
Hi,

I saw the timings report and would assume that the saveplayers task produces this behaviour.
It is the only scheduled task in the main class and runs every 10mins by default if I remeber correctly.
Could you send me your current config (with database section removed)?
That might help with analysing this issue.
And are you using mysql or yaml?
Thank you for the detailed report and Ill fix this as soon as I get home.
Probably a Problem with Changes I made to yaml or mysql implementation.
Didnt notice the same behaviour on my server so far, so it is probably related to the yaml storage.

**Comment by TamrielNetwork** [comment] 2022-03-21 19:52
I made some tests myself and couldn't reproduce this error.
I tried to have a starting point to compare changes to, but didn't notice the same effect.
For me to solve this issue and know why it exists, I need your config.yml; players.yml and maybe boosters.yml.
Also, did you make any changes to the code that aren't in the release?
Maybe you also got some errors in console, that might make it easier for me to solve this.
Ill try to resolve this asap, I just need some details on when it is reproducable.

I was using 1.4.1 (From spigot & also tested github) and paper 1.18.2 #267.
This is my timings for my local testserver with all boosters active (From 3 of my accounts):
https://timings.aikar.co/?id=f83175f18c3a4e96b07e6ae63f3bfc6a

**Comment by TamrielNetwork** [comment] 2022-03-21 19:56
It may also be because you made manual changes to players.yml or boosters.yml.
That will mess with loading and saving for sure. If you could send me the players.yml I could test and verify for myself or see if there are any obvious errors in the yaml

**Comment by TamrielNetwork** [comment] 2022-03-22 00:59
Since I can't confirm or reproduce the issue, I made the task async.
Meaning it shouldn't affect performance of the main thread, thus probably resolving your problem!
I also removed a save task, that I added seemingly by mistake to the clear method of player yaml storage.
Try [this](https://github.com/TamrielNetwork/GBooster/releases/tag/1.4.1-alpha.0) release and tell me if that solves your issue. If not, it'd 100% help to have some more info on this!

**Comment by cobrex1** [comment] 2022-03-22 19:21
Hi and hope you are well, sorry IO have not been contributing, and for the delay in my replies. IRL work is hectic right now. 
Thanks for all the updates and keeping your plugin alive.
Yes that looks to have fixed the issues, thank you, been running the test version for over an hour, and no spikes.

**Closed** 2022-03-22 19:57 UTC
Labels: bug, question
